apiVersion: v1
kind: Namespace
metadata:
  name: srs-dev
  labels:
    app.kubernetes.io/name: script-runtime-service
    app.kubernetes.io/instance: script-runtime-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: srs-admin
  namespace: srs-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manage-configs
  namespace: srs-dev
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manage-srs-setup
  namespace: srs-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manage-configs
subjects:
- kind: ServiceAccount
  name: srs-admin
